# Generated by Django 3.1.7 on 2021-03-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_brand_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
