# Generated by Django 3.1.7 on 2021-03-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_checkout_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='checkout',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
